apiVersion: v1
kind: Service
metadata:
  name: aksauto326wf
  namespace: aksauto326-ns
  labels:
    app.kubernetes.io/name: aksauto326wf
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: aksauto326wf
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000